In [79]:
import pandas as pd
import numpy as np

In [73]:
bit_senti = pd.read_csv(r"C:\Users\Lenovo\OneDrive\빅데이터분석&활용팀플\csv outputs\bit_tweets_class.csv")
bit_senti.head()

C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (3,4,8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,user_name,user_description,user_followers,user_friends,user_favourites,date,text,hashtags,is_retweet,cleaned_tweets,subjectivity,polarity,sentiment
0,DeSota Wilson,"Biz Consultant, real estate, fintech, startups...",8534.0,7605,4838,2021-02-10 23:59:04,Blue Ridge Bank shares halted by NYSE after #b...,['bitcoin'],False,Blue Ridge Bank share halted NYSE ATM announce...,0.1,0.00,neutral
1,CryptoND,😎 BITCOINLIVE is a Dutch platform aimed at inf...,6769.0,1532,25483,2021-02-10 23:58:48,"😎 Today, that's this #Thursday, we will do a ""...","['Thursday', 'Btc', 'wallet', 'security']",False,Today Take friend expe,0.0,0.00,neutral
2,Crypto is the future,I will post a lot of buying signals for BTC tr...,625.0,129,14,2021-02-10 23:54:33,$BTC A big chance in a billion! Price: \487264...,"['Bitcoin', 'FX', 'BTC', 'crypto']",False,BTC A big chance billion Price,0.1,0.00,neutral
3,Alex Kirchmaier 🇦🇹🇸🇪 #FactsSuperspreader,Co-founder @RENJERJerky | Forbes 30Under30 | I...,1249.0,1472,10482,2021-02-10 23:54:06,This network is secured by 9 508 nodes as of t...,['BTC'],False,This network secured node today Soon biggest b...,0.2,-0.25,negative
4,ZerrBenz™ ⚔ ✪ 20732,I'm a cat slave 🐱 Interested in Blockchain · T...,742.0,716,2444,2021-02-10 23:53:30,💹 Trade #Crypto on #Binance \n\n📌 Enjoy #Cashb...,"['Crypto', 'Binance', 'Cashback']",False,Trade Enjoy Trading fee Sign link,0.5,0.40,positive

In [74]:
#column순서 변경
bit_senti = bit_senti[['date', 'user_name', 'user_description', 'user_followers', 'user_friends',
       'user_favourites', 'text', 'hashtags', 'is_retweet',
       'cleaned_tweets', 'subjectivity', 'polarity', 'sentiment']]

In [75]:
#슬라이싱하여 추출할 날짜 텍스트 확인
date = bit_senti['date'][3][:10]
date

'2021-02-10'

In [76]:
dtList = []
for i in range(bit_senti.shape[0]):
    date = bit_senti['date'][i][:10]
    dtList.append(date)
    
bit_senti['only_date'] = dtList

bit_senti.tail()

,date,user_name,user_description,user_followers,user_friends,user_favourites,text,hashtags,is_retweet,cleaned_tweets,subjectivity,polarity,sentiment,only_date
1734667,2021-11-12 20:27:16,JomCRYPTO,Developer,5.0,41,394,@WatcherGuru #Btc\n#ETH \n#LTC \n#COSMOS \n#St...,"['Btc', 'ETH', 'LTC', 'COSMOS', 'Stellar', 'Do...",False,Dogs,0.000000,0.000000,neutral,2021-11-12
1734668,2021-11-12 20:27:15,Ali,NaN,80.0,217,191,@TheBitcoinConf @priceoftomorrow @addyinvest @...,"['shib', 'shiba', 'shiba_army', 'shibaw', 'shi...",False,Calm We go moon soon The new Shiba It x Unveil...,0.602273,0.218182,positive,2021-11-12
1734669,2021-11-12 20:27:08,Muhammed,NaN,34.0,81,3695,@Heatherfernsby #pitbulltoken will be the doge...,"['pitbulltoken', 'pitbull', 'PitbullToken100x'...",False,dogecoin future huge investor base,0.675000,-0.133333,negative,2021-11-12
1734670,2021-11-12 20:27:08,Francesco Santoro $VET,"Investitore #BNB , #CRO e #VET appassionato d...",76.0,354,1011,I am changing the way I invest. In the wallet ...,"['VET', 'btc', 'BNB']",False,I changing way I invest In wallet The rest fun...,0.000000,0.000000,neutral,2021-11-12
1734671,2021-11-12 20:27:05,GROND,Investor / Misantrophe / Fudie\n\nPyramid sche...,17.0,41,594,@LucaLand97 It is absolutely unbelievable. And...,['BTC'],False,It absolutely unbelievable And price hardly re...,0.770833,-0.270833,negative,2021-11-12

In [77]:
bit_senti2 = bit_senti
bit_senti2.columns

Index(['date', 'user_name', 'user_description', 'user_followers',
       'user_friends', 'user_favourites', 'text', 'hashtags', 'is_retweet',
       'cleaned_tweets', 'subjectivity', 'polarity', 'sentiment', 'only_date'],
      dtype='object')

In [82]:
bit_senti2.to_csv(r"C:\Users\Lenovo\OneDrive\빅데이터분석&활용팀플\csv outputs\bit_senti2(onlyDate).csv")

In [2]:
import pandas as pd
import numpy as np

In [3]:
bit_senti2 = pd.read_csv(r"C:\Users\Lenovo\OneDrive\빅데이터분석&활용팀플\csv outputs\bit_senti2(onlyDate).csv")

C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (5,6,9) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [53]:
aaa = bit_senti2[['subjectivity','polarity','only_date']]
print(aaa.columns)
aaa.head()

Index(['subjectivity', 'polarity', 'only_date'], dtype='object')

   subjectivity  polarity   only_date
0           0.1      0.00  2021-02-10
1           0.0      0.00  2021-02-10
2           0.1      0.00  2021-02-10
3           0.2     -0.25  2021-02-10
4           0.5      0.40  2021-02-10

In [54]:
aa= aaa.groupby(['only_date']).mean()
print(aa.shape)
aa

(100, 2)

            subjectivity  polarity
only_date
2021-02-05      0.243801  0.084413
2021-02-06      0.257014  0.097354
2021-02-07      0.326438  0.144448
2021-02-08      0.249640  0.091342
2021-02-09      0.245403  0.092980
...                  ...       ...
['YieldFar      0.000000  0.000000
['bitcoin'      0.000000  0.000000
['btc']         0.000000  0.000000
['cryptocu      0.000000  0.000000
['cryptotr      0.000000  0.000000

[100 rows x 2 columns]

In [55]:
print(type(bit_senti2['only_date'][2]))

<class 'str'>

In [56]:
aa.index.name = 'date'
aa.reset_index(drop = False, inplace = True)
aa

          date  subjectivity  polarity
0   2021-02-05      0.243801  0.084413
1   2021-02-06      0.257014  0.097354
2   2021-02-07      0.326438  0.144448
3   2021-02-08      0.249640  0.091342
4   2021-02-09      0.245403  0.092980
..         ...           ...       ...
95  ['YieldFar      0.000000  0.000000
96  ['bitcoin'      0.000000  0.000000
97     ['btc']      0.000000  0.000000
98  ['cryptocu      0.000000  0.000000
99  ['cryptotr      0.000000  0.000000

[100 rows x 3 columns]

In [57]:
import re  #정규표현식

In [59]:
from tqdm import tqdm
import progressbar

for i in tqdm(range(80, 100)):
    dt_regex = re.compile('[a-z]', re.I)
    valid = dt_regex.search(aa['date'][i])
    if valid:
        aa.drop(index =i ,axis =0, inplace = True)
    else:
        pass

print(aa)

100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 1981.53it/s]

          date  subjectivity  polarity
0   2021-02-05      0.243801  0.084413
1   2021-02-06      0.257014  0.097354
2   2021-02-07      0.326438  0.144448
3   2021-02-08      0.249640  0.091342
4   2021-02-09      0.245403  0.092980
..         ...           ...       ...
87  2021-11-04      0.349635  0.169745
88  2021-11-05      0.355022  0.165330
89  2021-11-06      0.351870  0.167605
90  2021-11-11      0.333200  0.148472
91  2021-11-12      0.347929  0.158708

[92 rows x 3 columns]

In [60]:
aa

          date  subjectivity  polarity
0   2021-02-05      0.243801  0.084413
1   2021-02-06      0.257014  0.097354
2   2021-02-07      0.326438  0.144448
3   2021-02-08      0.249640  0.091342
4   2021-02-09      0.245403  0.092980
..         ...           ...       ...
87  2021-11-04      0.349635  0.169745
88  2021-11-05      0.355022  0.165330
89  2021-11-06      0.351870  0.167605
90  2021-11-11      0.333200  0.148472
91  2021-11-12      0.347929  0.158708

[92 rows x 3 columns]

In [61]:
aa.to_csv(r"C:\Users\Lenovo\OneDrive\빅데이터분석&활용팀플\csv outputs\3col_1.csv")